### ISSUE TITLE
Log rotation failing [seems] to crash the process

### ISSUE THREAD

**Issue by vikaspotluri123** [gradebook/server#33]
```
Error: EACCES: permission denied, open './logs/error.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: './logs/error.log'
}
events.js:187
      throw er; // Unhandled 'error' event
```

The process shouldn't crash if rotation fails

**Comment by vikaspotluri123** [comment]
I did some further research. It looks like it won't be possible to catch this error because the error comes from a write stream which, by definition is async. This error originates in Bunyan so there's not much we can do to fix it.
